### ISSUE TITLE
[DISCUSS] EMS Localization

### ISSUE THREAD

**Issue by nickpeihl** [elastic/ems-file-service#56]
Related to https://github.com/elastic/kibana/issues/23407

Localization in EMS will require changes to the EMS manifests and Kibana.

Region maps in Kibana will need to access the `locale` setting in `kibana.yml` and use that to determine which vector manifest to choose from the catalogue manifest ([modifying this function](https://github.com/elastic/kibana/blob/master/src/ui/public/vis/map/service_settings.js#L89-L104)).

## Catalogue manifest schema

Here's a first draft of how I think the catalogue manifest would appear for the vector layers. We would generate different vector manifests for each locale in the `i18n` dictionary and fall back to the top level `manifest` if necessary.. The list of locales should match the locales in the [kbn-i18n package ](https://github.com/elastic/kibana/blob/f522b31ac986d10e38f487055f70c1e8350ee741/packages/kbn-i18n/src/core/locales.js). Note, I haven't changed anything in the `tiles_v2` element, but that could change, too, depending on how we handle basemap internationalization.

```json
{
  "services": [
    {
      "id": "tiles_v2",
      "name": "Elastic Maps Tile Service",
      "manifest": "https://tiles.maps.elastic.co/v2/manifest",
      "type": "tms"
    },
    {
      "id": "geo_layers",
      "name": "Elastic Maps Vector Service",
      "manifest": "https://vector.maps.elastic.co/v6.6/en-US/manifest",
      "type": "file",
      "i18n": { 
        "af": {
          "manifest": "https://vector.maps.elastic.co/v6.6/af/manifest"
        },
        ...,
        "es": {
          "manifest": "https://vector.maps.elastic.co/v6.6/es/manifest"
        },
        ...,
      }
    }
  ]
}
```

## Vector manifests schema 

Here is an example of how I assume the Spanish locale vector manifest would appear (https://vector.maps.elastic.co/v6.6/es/manifest). The top level `name` property in each layer must remain the same to avoid breaking visualizations but a `description` property is added which could be used as the `label` in the select box instead of the `name` property. This would be similar to how the [`description` property in the `fields` is used](https://github.com/elastic/kibana/blob/master/src/core_plugins/region_map/public/region_map_vis_params.html#L36-L48). 

```json
{
  "layers": [
    {
      "attribution": "[Made with NaturalEarth](http://www.naturalearthdata.com/about/terms-of-use)|[Elastic Maps Service](https://www.elastic.co/elastic-maps-service)",
      "weight": 1,
      "name": "World Countries",
      "description": "País",
      "url": "https://vector.maps.elastic.co/files/world_countries_v1.geo.json?elastic_tile_service_tos=agree",
      "format": "geojson",
      "fields": [
        {
          "type": "id",
          "name": "iso2",
          "description": "ISO 3166-1 alpha-2"
        },
        {
          "type": "id",
          "name": "iso3",
          "description": "ISO 3166-1 alpha-3"
        },
        {
          "type": "property",
          "name": "name",
          "description": "Nombre"
        },
      ],
      "created_at": "2017-04-26T17:12:15.978370",
      "tags": [],
      "id": 5659313586569216
    },
   ...,
    {
      "attribution": "© [OpenStreetMap](https://www.openstreetmap.org/copyright) contributors|[Elastic Maps Service](https://www.elastic.co/elastic-maps-service)",
      "weight": 0,
      "name": "Provincia de Canadá",
      "url": "https://vector.maps.elastic.co/files/canada_provinces_v1.geo.json?elastic_tile_service_tos=agree",
      "format": "geojson",
      "fields": [
        {
          "type": "id",
          "name": "iso_3166_2",
          "description": "ISO-3166-2"
        },
        {
          "type": "property",
          "name": "label_en",
          "description": "Nombre (inglés)"
        },
        {
          "type": "property",
          "name": "label_fr",
          "description": "Nombre (francés)"
        }
      ],
      "created_at": "2018-01-23T13:07:00.346990",
      "tags": [],
      "id": 5715999101812736
    },
    ...
  ]
}
```

I'm sure there are unanswered questions and probably other things I haven't considered. So please let me know your thoughts @elastic/kibana-gis.

**Comment by nyurik** [comment]
If we want the minimum changes, I think we should simply replace language-strings with multilingual objects. E.g. the v2/manifest would only need attribution localized (note that URLs might also be different for different languages)

```json
{
  "services": [
    {
      "id": "road_map",
      "url": "https://tiles.maps.elastic.co/v2/default/{z}/{x}/{y}.png?elastic_tile_service_tos=agree&my_app_name=kibana",
      "minZoom": 0,
      "maxZoom": 10,
      "attribution": {
        "en": "© [OpenStreetMap](http://www.openstreetmap.org/copyright) contributors | [Elastic Maps Service](https://www.elastic.co/elastic-maps-service)",
        "fr": "..."
    }
  ]
}
```

For a more thorough update, which would also speed up things a bit, we may need to put all of the available tiles and ems files into a single catalogue. Note that we should re-download that catalogue in each browser session to avoid our previous caching issues.

```yaml
{
  "version": "v7",
  "id": "catalogue",
  "base-maps": [
    {
      "id": "road_map",
      "raster": "http://tiles../raster/style.json",   // <-- this could in some cases also be per lang object
      "vector": "http://tiles../vector/style.json",  // <-- same
      "name": {
        "en": "...",
        "fr": "..."
      },
      "description": {
        "en": "...",
        "fr": "..."
      }
    }
  ],
  "emsfiles": [
    {
      "id": "us_states",
      "geojson": "http://tiles../...geo.json",
      "topojson": "http://tiles../...topo.json",
      "name": {
        "en": "...",
        "fr": "..."
      },
      "description": {
        "en": "...",
        "fr": "..."
      }
    }
  ]
}
```
